version: "3.8"

services:
  proxy-api:
    build: ./proxy/
    volumes: 
        - ./proxy/:/usr/src/app/
    ports: 
        - 8000:8000
    environment:
        DEBUG: 1
        ENVIRONMENT: development
    networks:
      example-network:
        ipv4_address: 172.16.238.10

  app-prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: app-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      example-network:
        ipv4_address: 172.16.238.11

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
