version: "3"

services:

  proxy-api:
    build: ./proxy/
    volumes: 
        - ./proxy/:/usr/src/app/
    ports: 
        - 8000:8000
    environment:
        DEBUG: 1
        ENVIRONMENT: development
    networks:
      node-network:
        ipv4_address: 172.16.238.10
    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      node-network:
        ipv4_address: 172.16.238.11

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    logging:
      options:
          max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      node-network:
        ipv4_address: 172.16.238.12

networks:
  node-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
