site_name: API Proxy
site_url: https://github.com/FernandoCelmer/api-proxy
repo_url: https://github.com/FernandoCelmer/api-proxy
repo_name: api-proxy
copyright: Fernando Celmer

nav:
    - Home: index.md
    - Projeto:
      - nav/project/flow.md
      - nav/project/execution.md
      - nav/project/permissions-structure.md
      - nav/project/technologies.md
    - Documentação:
      - nav/documentation/mkdocs.md
      - nav/documentation/swagger.md
    - Configurações:
      - nav/settings/python-virtual-environment.md
      - nav/settings/environment-variables.md
    - Monitoramento:
      - nav/monitoring/prometheus.md

theme:
    name: material
    palette:
        primary: black

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FernandoCelmer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fernando-celmer/
